config/routes.rb
Rails.application.routes.draw do
  # get '/' => 'cars#index', as: 'root'
  root 'cars#index'

  # resources :cars

  # get 'cars' => 'cars#index', as: 'cars'

  get 'cars/new' => 'cars#new', as: 'new_car'

  post 'cars' => 'cars#create'

  get 'cars/:id/edit' => 'cars#edit', as: 'edit_car'

  get 'cars/:id' => 'cars#show', as: 'car'

  patch 'cars/:id' => 'cars#update'

  put 'cars/:id' => 'cars#update'

  # delete 'cars/:id' => 'cars#destroy'

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:edit, :update]

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def create
    @car = Car.new(car_params)
    creation_message = "#{@car.year} #{@car.make} #{@car.model} has been created"
    redirect_to root_path,
      notice: creation_message
    @car.save
  end

  def update
    @car.update(car_params)
    update_message = "#{@car.year} #{@car.make} #{@car.model} has been updated"
    redirect_to root_path,
      notice: update_message
  end

  private
  def car_params
    params.require(:car).permit(:make, :model, :year, :price)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <div class="field">
    <%= f.label :make %>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h2>Edit Car</h2>

<%= render 'cars/form' %>

app/views/cars/index.html.erb
<%= link_to 'New Car', new_car_path %>

<table id="car_table" border="5 px" width="500px">
  <thead>
    <tr>
      <th>Year</th>
      <th>Make</th>
      <th>Model</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.year %></td>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= number_to_currency(car.price) %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= render 'cars/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |flash_type, message| %>
  <div class='flash' id='<%= flash_type %>'>
      <%= message %>
  </div>
<% end %>

<%= yield %>

</body>
</html>